const AR_DIACRITICS=/[\u064B-\u065F\u0670\u06D6-\u06ED]/g;
function normalizeArabic(value=''){return String(value).normalize('NFKC').replace(AR_DIACRITICS,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim().toLowerCase();}
function tokens(value=''){return normalizeArabic(value).split(' ').filter(Boolean);}
function overlap(a,b){const A=new Set(tokens(a)),B=new Set(tokens(b)); if(!A.size||!B.size)return 0; let n=0; for(const x of A)if(B.has(x))n++; return n/Math.max(A.size,B.size);}
function aliasesOf(person){return [person.canonicalName,person.displayName,person.nameAr,person.nameEn,...(person.aliases||[])].filter(Boolean);}
function exactAlias(person,mention){const n=normalizeArabic(mention); return aliasesOf(person).some(x=>normalizeArabic(x)===n);}
function nameCompatibility(person,mention){const m=tokens(mention); if(!m.length)return 0; let best=0; for(const alias of aliasesOf(person)){const a=tokens(alias); if(!a.length)continue; const same=m.every(t=>a.includes(t))||a.every(t=>m.includes(t)); const score=same?Math.min(m.length,a.length)/Math.max(m.length,a.length):overlap(alias,mention)*.8; best=Math.max(best,score);} return best;}
function contextScore(person,context={}){const hay=normalizeArabic([context.text,context.program,context.episodeTitle,context.location,context.occupation,...(context.tags||[])].filter(Boolean).join(' ')); const attrs=[person.occupation,person.titleAr,person.location,person.program,...(person.tags||[])].filter(Boolean); if(!hay||!attrs.length)return 0; const hits=attrs.filter(x=>hay.includes(normalizeArabic(x))).length; return Math.min(1,hits/Math.max(1,attrs.length));}
class PersonEntityResolver{
 constructor(repository,{highThreshold=.86,reviewThreshold=.58}={}){this.repository=repository;this.highThreshold=highThreshold;this.reviewThreshold=reviewThreshold;}
 candidates(mention,context={}){const people=this.repository.list('people',{limit:Number.MAX_SAFE_INTEGER}); const first=tokens(mention)[0]; return people.map(person=>{const exact=exactAlias(person,mention); const name=nameCompatibility(person,mention); const ctx=contextScore(person,context); const recent=context.recentPersonId===person.id?1:0; const firstMatch=first&&aliasesOf(person).some(a=>tokens(a)[0]===first)?1:0; let score=exact?1:(name*.68+ctx*.17+recent*.1+firstMatch*.05); if(tokens(mention).length===1&&!recent)score=Math.min(score,.79); return {person,score:Number(score.toFixed(3)),reasons:{exactAlias:exact,nameCompatibility:Number(name.toFixed(3)),context:Number(ctx.toFixed(3)),recentPerson:!!recent,firstNameMatch:!!firstMatch}};}).filter(x=>x.score>=.2).sort((a,b)=>b.score-a.score);}
 resolveMention(input={}){const text=String(input.text||'').trim(); if(!text)throw new Error('mention text is required'); const candidates=this.candidates(text,input.context||{}); const top=candidates[0]; const runner=candidates[1]; let status='unresolved',resolvedPersonId=null; if(top&&top.score>=this.highThreshold&&(!runner||top.score-runner.score>=.12)){status='resolved';resolvedPersonId=top.person.id;} else if(top&&top.score>=this.reviewThreshold){status='review_required';}
 const mention=this.repository.upsert('mentions',{text,normalizedText:normalizeArabic(text),transcriptId:input.transcriptId||null,episodeId:input.episodeId||null,startTime:input.startTime??null,endTime:input.endTime??null,speakerId:input.speakerId||null,context:input.context||{},status,resolvedPersonId,confidence:top?.score||0,candidates:candidates.slice(0,5).map(x=>({personId:x.person.id,score:x.score,reasons:x.reasons}))});
 if(resolvedPersonId)this.repository.link({fromType:'mentions',fromId:mention.id,toType:'people',toId:resolvedPersonId,relation:'refers_to'}); return {...mention,candidatePeople:candidates.slice(0,5).map(x=>({person:x.person,score:x.score,reasons:x.reasons}))};}
 review(mentionId,action,personId=null){const mention=this.repository.get('mentions',mentionId); if(!mention)throw new Error('mention not found'); if(action==='resolve'){if(!personId||!this.repository.get('people',personId))throw new Error('valid personId is required'); const next=this.repository.upsert('mentions',{...mention,status:'resolved',resolvedPersonId:personId,reviewedAt:new Date().toISOString(),reviewAction:'resolve'}); this.repository.link({fromType:'mentions',fromId:mentionId,toType:'people',toId:personId,relation:'refers_to'}); return next;} if(action==='new_person'){const person=this.repository.upsert('people',{canonicalName:mention.text,displayName:mention.text,nameAr:mention.text,aliases:[mention.text],source:'identity_review'}); return this.review(mentionId,'resolve',person.id);} if(action==='defer')return this.repository.upsert('mentions',{...mention,status:'deferred',reviewedAt:new Date().toISOString(),reviewAction:'defer'}); throw new Error('unknown review action');}
 mergePeople(primaryId,duplicateId,{reason='manual_merge'}={}){if(primaryId===duplicateId)throw new Error('cannot merge the same person'); const primary=this.repository.get('people',primaryId),duplicate=this.repository.get('people',duplicateId); if(!primary||!duplicate)throw new Error('person not found'); const snapshot={primary,duplicate,links:this.repository.list('links',{limit:Number.MAX_SAFE_INTEGER}).filter(l=>[primaryId,duplicateId].includes(l.fromId)||[primaryId,duplicateId].includes(l.toId)),mentions:this.repository.list('mentions',{limit:Number.MAX_SAFE_INTEGER}).filter(m=>[primaryId,duplicateId].includes(m.resolvedPersonId))}; const aliases=[...new Set([...aliasesOf(primary),...aliasesOf(duplicate)])]; const merged=this.repository.upsert('people',{...primary,aliases,mergedFrom:[...(primary.mergedFrom||[]),duplicateId]}); const db=this.repository.read(); db.links=db.links.map(l=>({...l,fromId:l.fromType==='people'&&l.fromId===duplicateId?primaryId:l.fromId,toId:l.toType==='people'&&l.toId===duplicateId?primaryId:l.toId})); db.mentions=db.mentions.map(m=>m.resolvedPersonId===duplicateId?{...m,resolvedPersonId:primaryId}:m); db.people=db.people.filter(p=>p.id!==duplicateId); const audit={id:`merge_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`,primaryId,duplicateId,reason,snapshot,createdAt:new Date().toISOString()}; db.identityAudits.push(audit); this.repository.write(db); return {merged,audit};}
 undoMerge(auditId){const db=this.repository.read(); const audit=db.identityAudits.find(x=>x.id===auditId); if(!audit||audit.undoneAt)throw new Error('active merge audit not found'); db.people=db.people.filter(p=>![audit.primaryId,audit.duplicateId].includes(p.id)); db.people.push(audit.snapshot.primary,audit.snapshot.duplicate); const affected=new Set(audit.snapshot.links.map(x=>x.id)); db.links=db.links.filter(l=>!affected.has(l.id)); db.links.push(...audit.snapshot.links); const mentionIds=new Set(audit.snapshot.mentions.map(x=>x.id)); db.mentions=db.mentions.map(m=>mentionIds.has(m.id)?audit.snapshot.mentions.find(x=>x.id===m.id):m); audit.undoneAt=new Date().toISOString(); this.repository.write(db); return audit;}
}
module.exports={PersonEntityResolver,normalizeArabic,nameCompatibility};
