const state={pickedFile:null,transcript:null,transcriptData:null,chapters:[],mogrtFolder:null,mogrtItems:[],lastSuggestions:null,projectSnapshot:null,currentPlan:null,taskFilter:"all"};

document.querySelectorAll(".tab-btn").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tab-btn").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".tab-content").forEach(c=>c.classList.remove("active"));btn.classList.add("active");document.getElementById("tab-"+btn.dataset.tab).classList.add("active");if(btn.dataset.tab==="tasks")renderTasks();}));

function saveSettings(){ApiKeys.save(document.getElementById("ollama-url").value.trim(),document.getElementById("ollama-model").value.trim(),document.getElementById("whisper-key").value.trim());localStorage.setItem("idurazi_safe_mode",document.getElementById("safe-mode").checked?"1":"0");}
(function initSettings(){const saved=ApiKeys.load();document.getElementById("ollama-url").value=saved.serviceUrl||"http://127.0.0.1:37841";document.getElementById("ollama-model").value=saved.ollamaModel||"qwen3:8b";document.getElementById("whisper-key").value=saved.whisper||"";document.getElementById("safe-mode").checked=localStorage.getItem("idurazi_safe_mode")!=="0";document.getElementById("save-keys").onclick=()=>{saveSettings();setStatus("save-status","تم حفظ الإعدادات.");};document.getElementById("test-ollama").onclick=testService;setTimeout(testService,300);})();
async function testService(){const status=document.getElementById("ollama-status");saveSettings();status.textContent="جاري الاختبار...";try{const r=await OllamaClient.testConnection();document.getElementById("service-dot").className="dot online";status.textContent=`الخدمة تعمل · ${r.models?.length||0} نموذج`;return r;}catch(e){document.getElementById("service-dot").className="dot offline";status.textContent="تعذر الاتصال: "+e.message;throw e;}}

async function refreshProject(){const box=document.getElementById("project-json");box.textContent="جاري القراءة...";try{state.projectSnapshot=await PremiereBridge.getProjectSnapshot();box.textContent=JSON.stringify(state.projectSnapshot,null,2);const s=state.projectSnapshot;document.getElementById("project-status").innerHTML=`<div class="status-card"><small>المشروع</small>${escapeHtml(s.projectName||"غير متاح")}</div><div class="status-card"><small>Sequence</small>${escapeHtml(s.sequenceName||"غير نشط")}</div>`;return s;}catch(e){box.textContent=e.message;return {error:e.message};}}
document.getElementById("refresh-project").onclick=refreshProject;

document.getElementById("send-copilot").onclick=async()=>{const input=document.getElementById("copilot-prompt");const prompt=input.value.trim();if(!prompt)return;appendMessage("user",prompt);input.value="";const btn=document.getElementById("send-copilot");btn.disabled=true;btn.textContent="جاري التخطيط...";try{let context=null;if(document.getElementById("include-project-context").checked)context=state.projectSnapshot||await refreshProject();const plan=await CopilotClient.plan(prompt,{project:context,transcript:state.transcript?state.transcript.slice(0,12000):null,safeMode:document.getElementById("safe-mode").checked});state.currentPlan=plan;appendMessage("assistant",plan.summary||"تم إنشاء الخطة.");renderPlan(plan);const created=TaskStore.addMany(plan.tasks||[],{planId:plan.planId});renderTasks();}catch(e){appendMessage("error","تعذر إنشاء الخطة: "+e.message);}finally{btn.disabled=false;btn.textContent="إنشاء خطة";}};
document.getElementById("new-session").onclick=()=>{document.getElementById("chat-log").innerHTML='<div class="message assistant">بدأت جلسة جديدة. جميع عمليات التعديل ستظل خاضعة للموافقة.</div>';document.getElementById("plan-preview").classList.add("hidden");state.currentPlan=null;};
function appendMessage(type,text){const el=document.createElement("div");el.className="message "+type;el.textContent=text;const log=document.getElementById("chat-log");log.appendChild(el);log.scrollTop=log.scrollHeight;}
function renderPlan(plan){const box=document.getElementById("plan-preview");box.classList.remove("hidden");const tasks=plan.tasks||[];box.innerHTML=`<h3>الخطة المقترحة (${tasks.length})</h3>`+tasks.map((t,i)=>`<div class="plan-step"><div class="task-head"><b>${i+1}. ${escapeHtml(t.title||t.action)}</b><span class="badge ${escapeHtml(t.risk||"low")}">${escapeHtml(t.risk||"low")}</span></div><div class="hint">${escapeHtml(t.description||"")}</div></div>`).join("")+`<p class="hint">انتقل إلى تبويب المهام لمراجعة كل خطوة وتنفيذها منفردة.</p>`;}

function renderTasks(){const tasks=TaskStore.load().filter(t=>state.taskFilter==="all"||t.status===state.taskFilter);const list=document.getElementById("tasks-list");if(!tasks.length){list.innerHTML='<p class="hint">لا توجد مهام في هذا القسم.</p>';return;}list.innerHTML=tasks.map(t=>`<div class="task-card"><div class="task-head"><b>${escapeHtml(t.title)}</b><span class="badge ${escapeHtml(t.risk)}">${escapeHtml(t.status)}</span></div><div class="hint">${escapeHtml(t.description||t.action)}</div><div class="task-actions">${t.status==="pending"?`<button class="primary-btn compact execute-task" data-id="${t.id}">موافقة وتنفيذ</button><button class="secondary-btn compact reject-task" data-id="${t.id}">رفض</button>`:""}</div>${t.result?`<pre class="code-box">${escapeHtml(typeof t.result==="string"?t.result:JSON.stringify(t.result,null,2))}</pre>`:""}</div>`).join("");document.querySelectorAll(".execute-task").forEach(b=>b.onclick=()=>executeTask(b.dataset.id));document.querySelectorAll(".reject-task").forEach(b=>b.onclick=()=>{TaskStore.update(b.dataset.id,{status:"rejected",result:"رفضها المستخدم"});renderTasks();});}
async function executeTask(id){const task=TaskStore.load().find(t=>t.id===id);if(!task)return;TaskStore.update(id,{status:"running"});renderTasks();try{const result=await PremiereBridge.executeCopilotTask(task);TaskStore.update(id,{status:"done",result:sanitizeResult(result)});if(task.action==="create_markers"){UndoStore.push({title:task.title,description:`تم إنشاء ${result.count||0} Markers`,action:task.action}, {createdMarkers:result.createdMarkers||[]});}else{UndoStore.push({title:task.title,description:"تم تنفيذ العملية وتسجيلها.",action:task.action,reversible:false});}renderUndoHistory();}catch(e){TaskStore.update(id,{status:"failed",result:e.message||String(e)});}renderTasks();}
function sanitizeResult(v){try{return JSON.parse(JSON.stringify(v));}catch(_){return String(v);}}
document.querySelectorAll(".filter-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.taskFilter=b.dataset.filter;renderTasks();});document.getElementById("clear-history").onclick=()=>{TaskStore.clear();renderTasks();};

document.getElementById("pick-audio-file").onclick=async()=>{try{const f=await PremiereBridge.pickAudioOrVideoFile();if(!f)return;state.pickedFile=f;document.getElementById("picked-file-name").textContent=f.name;document.getElementById("run-transcribe").disabled=false;}catch(e){alert(e.message);}};
document.getElementById("use-manual-transcript").onclick=()=>{const t=document.getElementById("manual-transcript").value.trim();if(!t)return alert("الصق الترانسكريبت أولًا.");state.transcript=t;state.transcriptData=null;document.getElementById("transcript-text").textContent=t;document.getElementById("transcript-meta").textContent="نص يدوي";document.getElementById("transcript-output").classList.remove("hidden");document.getElementById("run-analyze").disabled=false;document.getElementById("generate-chapters").disabled=false;};
document.getElementById("run-transcribe").onclick=async()=>{toggleProgress("transcribe",true);try{const nativePath=PremiereBridge.getNativePath(state.pickedFile);const data=await LocalTranscriptionClient.transcribe(nativePath,{language:document.getElementById("whisper-language").value,model:document.getElementById("whisper-model").value});state.transcriptData=data;state.transcript=data.text||"";document.getElementById("transcript-text").textContent=state.transcript;document.getElementById("transcript-meta").textContent=`اللغة: ${data.language||"غير معروفة"} · المقاطع: ${(data.segments||[]).length} · المحرك: faster-whisper`;document.getElementById("transcript-files").textContent=data.files?`تم الحفظ محليًا: ${Object.values(data.files).join(" | ")}`:"";document.getElementById("transcript-output").classList.remove("hidden");document.getElementById("run-analyze").disabled=false;document.getElementById("generate-chapters").disabled=false;}catch(e){alert("فشل التفريغ المحلي: "+(e.message||e));}finally{toggleProgress("transcribe",false);}};
document.getElementById("run-analyze").onclick=async()=>{if(!state.transcript)return alert("اعتمد الترانسكريبت أولًا.");toggleProgress("analyze",true);try{const r=await OllamaClient.analyzeAndSuggest(state.transcript,IDURAZI_TEMPLATES);state.lastSuggestions=Array.isArray(r.suggestions)?r.suggestions:[];renderSuggestions();document.getElementById("analyze-output").classList.remove("hidden");}catch(e){alert(e.message);}finally{toggleProgress("analyze",false);}};

document.getElementById("pick-mogrt-folder").onclick=async()=>{try{const f=await PremiereBridge.pickMogrtFolder();if(!f)return;state.mogrtFolder=f;document.getElementById("mogrt-folder-name").textContent=f.name;await scanMogrts(f);}catch(e){alert(e.message);}};document.getElementById("scan-mogrts").onclick=()=>scanMogrts(state.mogrtFolder||undefined).catch(e=>alert(e.message));async function scanMogrts(folder){state.mogrtItems=await PremiereBridge.scanMogrtItems(folder);document.getElementById("mogrt-list").innerHTML=`<p class="hint">تم العثور على ${state.mogrtItems.length} قالب.</p>`;updateTemplateMatchStatus(state.mogrtItems);}
async function insertSuggestion(idx){const s=state.lastSuggestions?.[idx];if(!s)return;try{if(!state.mogrtItems.length)await scanMogrts();const item=PremiereBridge.findMogrtByCode(state.mogrtItems,s.templateCode);if(!item)throw new Error("القالب غير موجود");const track=Number(document.getElementById("target-track").value)||2;await PremiereBridge.insertMogrtAtTime(item.nativePath,s.timeSeconds,track,s.textFields||{});alert("تم الإدراج بنجاح");}catch(e){alert(e.message);}}
function renderSuggestions(){const list=document.getElementById("suggestions-list");list.innerHTML="";state.lastSuggestions.forEach((s,i)=>{const c=document.createElement("div");c.className="suggestion-card";c.innerHTML=`<div class="suggestion-time">${formatSeconds(Number(s.timeSeconds)||0)}</div><div>${escapeHtml(s.reason||"")}</div><div class="suggestion-graphic">${escapeHtml(s.templateCode||"")}</div><button class="secondary-btn insert-btn" data-idx="${i}">إدراج بعد المراجعة</button>`;list.appendChild(c);});document.querySelectorAll(".insert-btn").forEach(b=>b.onclick=()=>insertSuggestion(Number(b.dataset.idx)));}
function toggleProgress(p,on){document.getElementById(p+"-progress").classList.toggle("hidden",!on)}function formatSeconds(v){return `${Math.floor(v/60).toString().padStart(2,"0")}:${Math.floor(v%60).toString().padStart(2,"0")}`}function escapeHtml(v){const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML}function setStatus(id,t){const e=document.getElementById(id);e.textContent=t;setTimeout(()=>e.textContent="",2500)}
(async()=>{try{const f=await PremiereBridge.getSavedMogrtFolder();if(f){state.mogrtFolder=f;document.getElementById("mogrt-folder-name").textContent=f.name;}}catch(_){}renderTasks();})();

function parseTimecode(value){
  const p=String(value||"").trim().split(":").map(Number);
  if(p.some(Number.isNaN)) return NaN;
  if(p.length===3) return p[0]*3600+p[1]*60+p[2];
  if(p.length===2) return p[0]*60+p[1];
  if(p.length===1) return p[0];
  return NaN;
}
function parseManualMarkers(text,colorIndex){
  return String(text||"").split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map((line,i)=>{
    const parts=line.split("|").map(x=>x.trim());
    return {timeSeconds:parseTimecode(parts[0]),name:parts[1]||`Marker ${i+1}`,comments:parts[2]||"",durationSeconds:0,colorIndex:Number(colorIndex)||0,markerType:"Comment"};
  }).filter(x=>Number.isFinite(x.timeSeconds));
}
async function readTimeline(){
  const box=document.getElementById("timeline-json"); box.textContent="جاري قراءة المسارات والمقاطع...";
  try{
    const snap=await PremiereBridge.getTimelineSnapshot();
    box.textContent=JSON.stringify(snap,null,2);
    document.getElementById("timeline-summary").innerHTML=`<div class="status-card"><small>Video Clips</small>${snap.totals.videoClips}</div><div class="status-card"><small>Audio Clips</small>${snap.totals.audioClips}</div><div class="status-card"><small>Markers</small>${snap.markers.length}</div>`;
    return snap;
  }catch(e){box.textContent=e.message||String(e);throw e;}
}
document.getElementById("read-timeline").onclick=()=>readTimeline().catch(e=>alert(e.message));
document.getElementById("preview-markers").onclick=()=>{
  const markers=parseManualMarkers(document.getElementById("manual-markers").value,document.getElementById("marker-color").value);
  if(!markers.length)return alert("لم أجد أسطرًا صالحة. استخدم: الوقت | الاسم | الملاحظة");
  TaskStore.addMany([{title:`إنشاء ${markers.length} Markers`,description:"ستضاف إلى الـSequence النشط بعد الموافقة.",action:"create_markers",risk:"medium",requiresApproval:true,parameters:{markers}}],{source:"manual-marker-preview"});
  state.taskFilter="all"; renderTasks(); document.querySelector('[data-tab="tasks"]').click();
};

function renderUndoHistory(){
  const items=UndoStore.load(), box=document.getElementById("undo-list");
  if(!items.length){box.innerHTML='<p class="hint">لا توجد عمليات منفذة بعد.</p>';return;}
  box.innerHTML=items.map(x=>`<div class="task-card"><div class="task-head"><b>${escapeHtml(x.title||x.action)}</b><span class="badge ${x.status==="undone"?"low":"medium"}">${escapeHtml(x.status)}</span></div><div class="hint">${escapeHtml(x.description||"")}</div><div class="hint">${x.reversible?"قابل للتراجع في الجلسة الحالية":"سجل فقط — لا يوجد تراجع آلي"}</div></div>`).join("");
}
document.getElementById("undo-last").onclick=async()=>{
  const item=UndoStore.latestReversible();
  if(!item)return alert("لا توجد عملية قابلة للتراجع في الجلسة الحالية.");
  try{
    const runtime=UndoStore.runtimeFor(item.id);
    if(item.action==="create_markers") await PremiereBridge.removeMarkers(runtime.data.createdMarkers);
    else throw new Error("لا يوجد منفذ تراجع لهذه العملية.");
    UndoStore.update(item.id,{status:"undone",reversible:false}); renderUndoHistory(); await readTimeline();
  }catch(e){alert("تعذر التراجع: "+(e.message||e));}
};
document.querySelector('[data-tab="history"]').addEventListener("click",renderUndoHistory);
renderUndoHistory();


document.getElementById("generate-chapters").onclick=async()=>{
  if(!state.transcript)return alert("قم بالتفريغ أو اعتماد النص أولًا.");
  toggleProgress("analyze",true);
  try{
    const timed=state.transcriptData?.segments?.length?state.transcriptData.segments.map(x=>`[${formatSeconds(x.start)}] ${x.text}`).join("\n"):state.transcript;
    const r=await LocalTranscriptionClient.chapters(timed,ApiKeys.load().model);
    state.chapters=Array.isArray(r.chapters)?r.chapters:[];
    const box=document.getElementById("chapters-list");
    box.innerHTML=state.chapters.map((c,i)=>`<div class="suggestion-card"><div class="suggestion-time">${formatSeconds(Number(c.timeSeconds)||0)}</div><b>${escapeHtml(c.title)}</b><div class="hint">${escapeHtml(c.summary||"")}</div></div>`).join("")||'<p class="hint">لم يتم العثور على فصول.</p>';
    document.getElementById("chapters-output").classList.remove("hidden");
  }catch(e){alert("تعذر إنشاء الفصول: "+(e.message||e));}
  finally{toggleProgress("analyze",false);}
};
document.getElementById("preview-chapters").onclick=()=>{
  if(!state.chapters.length)return alert("أنشئ الفصول أولًا.");
  const markers=state.chapters.map(c=>({timeSeconds:Number(c.timeSeconds)||0,name:c.title||"فصل",comments:c.summary||"",durationSeconds:0,colorIndex:Number(c.colorIndex)||2,markerType:"Chapter"}));
  TaskStore.addMany([{title:`إنشاء ${markers.length} Chapter Markers`,description:"فصول مستخرجة محليًا من الترانسكريبت، وستضاف بعد الموافقة.",action:"create_markers",risk:"medium",requiresApproval:true,parameters:{markers}}],{source:"smart-chapters"});
  state.taskFilter="all";renderTasks();document.querySelector('[data-tab="tasks"]').click();
};


// v2.1 People Repository + Smart Lower Thirds
state.people=[]; state.smartLowerThirds=[];
function personFormData(){return {id:document.getElementById('person-id').value||undefined,nameAr:document.getElementById('person-name-ar').value.trim(),titleAr:document.getElementById('person-title-ar').value.trim(),nameEn:document.getElementById('person-name-en').value.trim(),titleEn:document.getElementById('person-title-en').value.trim(),program:document.getElementById('person-program').value.trim(),templateCode:document.getElementById('person-template').value.trim()||'LT01',aliases:document.getElementById('person-aliases').value.split(',').map(x=>x.trim()).filter(Boolean),notes:document.getElementById('person-notes').value.trim()};}
function clearPersonForm(){['person-id','person-name-ar','person-title-ar','person-name-en','person-title-en','person-aliases','person-notes'].forEach(id=>document.getElementById(id).value='');document.getElementById('person-program').value='وجوه درازية';document.getElementById('person-template').value='LT01';}
async function loadPeople(){const r=await PeopleClient.list();state.people=r.people||[];const box=document.getElementById('people-list');box.innerHTML=state.people.map(p=>`<div class="task-card"><div class="task-head"><b>${escapeHtml(p.nameAr)}</b><span class="badge low">${escapeHtml(p.templateCode)}</span></div><div>${escapeHtml(p.titleAr||'بدون صفة')}</div><div class="hint">${escapeHtml(p.program||'')}</div><div class="task-actions"><button class="secondary-btn compact edit-person" data-id="${p.id}">تعديل</button><button class="danger-btn compact delete-person" data-id="${p.id}">حذف</button></div></div>`).join('')||'<p class="hint">لا يوجد أشخاص بعد.</p>';document.querySelectorAll('.edit-person').forEach(b=>b.onclick=()=>{const p=state.people.find(x=>x.id===b.dataset.id);if(!p)return;document.getElementById('person-id').value=p.id;document.getElementById('person-name-ar').value=p.nameAr||'';document.getElementById('person-title-ar').value=p.titleAr||'';document.getElementById('person-name-en').value=p.nameEn||'';document.getElementById('person-title-en').value=p.titleEn||'';document.getElementById('person-program').value=p.program||'';document.getElementById('person-template').value=p.templateCode||'LT01';document.getElementById('person-aliases').value=(p.aliases||[]).join(', ');document.getElementById('person-notes').value=p.notes||'';});document.querySelectorAll('.delete-person').forEach(b=>b.onclick=async()=>{if(!confirm('حذف هذا الشخص؟'))return;await PeopleClient.remove(b.dataset.id);await loadPeople();});}
document.getElementById('refresh-people').onclick=()=>loadPeople().catch(e=>alert(e.message));
document.getElementById('clear-person-form').onclick=clearPersonForm;
document.getElementById('save-person').onclick=async()=>{try{const p=personFormData();if(!p.nameAr)return alert('الاسم العربي مطلوب.');if(p.id)await PeopleClient.update(p);else await PeopleClient.create(p);clearPersonForm();await loadPeople();}catch(e){alert(e.message);}};
document.querySelector('[data-tab="people"]').addEventListener('click',()=>loadPeople().catch(()=>{}));
function renderSmartLT(){const box=document.getElementById('smart-lt-list');box.innerHTML=state.smartLowerThirds.map((s,i)=>`<div class="task-card"><div class="task-head"><b>${formatSeconds(Number(s.timeSeconds)||0)} · ${escapeHtml(s.textFields?.name||'')}</b><span class="badge ${s.confidence>=.75?'low':'medium'}">${Math.round((s.confidence||0)*100)}%</span></div><div>${escapeHtml(s.textFields?.role||'')}</div><div class="hint">${escapeHtml(s.reason||'')} · ${escapeHtml(s.templateCode||'LT01')}</div><button class="secondary-btn compact preview-one-lt" data-i="${i}">إرسال إلى المعاينة</button></div>`).join('')||'<p class="hint">لا توجد اقتراحات بعد.</p>';document.getElementById('preview-all-smart-lt').disabled=!state.smartLowerThirds.length;document.querySelectorAll('.preview-one-lt').forEach(b=>b.onclick=()=>queueSmartLT([state.smartLowerThirds[Number(b.dataset.i)]]));}
function queueSmartLT(items){const tasks=items.map(s=>({title:`Lower Third: ${s.textFields?.name||''}`,description:`${formatSeconds(Number(s.timeSeconds)||0)} · ${s.textFields?.role||''}`,action:'insert_mogrt',risk:'medium',requiresApproval:true,parameters:{templateCode:s.templateCode||'LT01',timeSeconds:Number(s.timeSeconds)||0,track:Number(document.getElementById('target-track').value)||2,textFields:s.textFields||{}}}));TaskStore.addMany(tasks,{source:'people-smart-lower-thirds'});renderTasks();document.querySelector('[data-tab="tasks"]').click();}
document.getElementById('generate-smart-lt').onclick=async()=>{if(!state.transcript)return alert('قم بالتفريغ أو اعتماد الترانسكريبت أولًا.');try{const timed=state.transcriptData?.segments?.length?state.transcriptData.segments.map(x=>`[${formatSeconds(x.start)}] ${x.text}`).join('\n'):state.transcript;const r=await PeopleClient.suggest(timed,ApiKeys.load().model);state.smartLowerThirds=r.suggestions||[];renderSmartLT();}catch(e){alert(e.message);}};
document.getElementById('preview-all-smart-lt').onclick=()=>queueSmartLT(state.smartLowerThirds);
renderSmartLT();

// v2.4 Archive Dashboard + Interview Import Pipeline
state.archiveResults=[];
const archiveLabels={people:'الأشخاص',episodes:'الحلقات',transcripts:'النصوص',topics:'الموضوعات',quotes:'الاقتباسات',assets:'الأصول',links:'العلاقات',imports:'عمليات الاستيراد'};
function archiveTitle(type,item){return item.title||item.nameAr||item.name||item.text?.slice(0,90)||item.id;}
function renderArchiveResults(items=[]){const box=document.getElementById('archive-results');box.innerHTML=items.map(r=>{const type=r.type||document.getElementById('archive-type').value;const item=r.item||r;return `<div class="task-card"><div class="task-head"><b>${escapeHtml(archiveTitle(type,item)||'سجل')}</b><span class="badge low">${escapeHtml(archiveLabels[type]||type)}</span></div><div class="hint">${escapeHtml(item.summary||item.description||item.titleAr||item.program||item.id||'')}</div><div class="task-actions"><button class="secondary-btn compact archive-linked" data-type="${type}" data-id="${item.id}">الروابط</button></div></div>`;}).join('')||'<p class="hint">لا توجد نتائج.</p>';document.querySelectorAll('.archive-linked').forEach(b=>b.onclick=async()=>{try{const r=await ArchiveClient.linked(b.dataset.type,b.dataset.id);renderArchiveResults((r.items||[]).map(x=>({type:x.type,item:x.item||{id:x.id,title:x.relation}})));}catch(e){alert(e.message);}});}
async function loadArchiveStats(){const r=await ArchiveClient.stats();document.getElementById('archive-stats').innerHTML=Object.entries(r.stats||{}).filter(([k])=>k!=='links').map(([k,v])=>`<div class="status-card"><small>${escapeHtml(archiveLabels[k]||k)}</small>${v}</div>`).join('');}
document.getElementById('refresh-archive').onclick=()=>loadArchiveStats().catch(e=>alert(e.message));
document.getElementById('archive-search').onclick=async()=>{try{const q=document.getElementById('archive-query').value.trim();if(!q)return alert('اكتب عبارة البحث.');const r=await ArchiveClient.search(q);state.archiveResults=r.results||[];renderArchiveResults(state.archiveResults);}catch(e){alert(e.message);}};
document.getElementById('archive-list-type').onclick=async()=>{try{const type=document.getElementById('archive-type').value;const r=await ArchiveClient.list(type);renderArchiveResults((r.items||[]).map(item=>({type,item})));}catch(e){alert(e.message);}};
document.querySelector('[data-tab="archive"]').addEventListener('click',()=>loadArchiveStats().catch(()=>{}));
document.getElementById('copy-current-transcript').onclick=()=>{document.getElementById('import-transcript').value=state.transcript||'';};
document.getElementById('run-interview-import').onclick=async()=>{const payload={title:document.getElementById('import-title').value.trim(),program:document.getElementById('import-program').value.trim(),episodeNumber:Number(document.getElementById('import-number').value)||null,summary:document.getElementById('import-summary').value.trim(),transcriptText:document.getElementById('import-transcript').value.trim(),guests:document.getElementById('import-guests').value.split(/\r?\n/).map(nameAr=>({nameAr:nameAr.trim()})).filter(x=>x.nameAr),topics:document.getElementById('import-topics').value.split(',').map(x=>x.trim()).filter(Boolean),language:'ar'};if(!payload.title||!payload.transcriptText)return alert('العنوان والترانسكريبت مطلوبان.');try{const r=await ArchiveClient.importInterview(payload);const x=r.result;const box=document.getElementById('import-result');box.classList.remove('hidden');box.innerHTML=`<h3>تم الاستيراد بنجاح</h3><div class="status-grid"><div class="status-card"><small>الحلقة</small>1</div><div class="status-card"><small>الأشخاص</small>${x.people.length}</div><div class="status-card"><small>الموضوعات</small>${x.topics.length}</div><div class="status-card"><small>الاقتباسات</small>${x.quotes.length}</div></div><div class="hint">Batch: ${escapeHtml(x.batchId)}</div>`;await loadArchiveStats();}catch(e){alert('تعذر الاستيراد: '+e.message);}};

// v2.5 Person Entity Resolution & Identity Review
function identityCard(m){const candidates=(m.candidatePeople||m.candidates||[]);const candidateHtml=candidates.map(c=>{const p=c.person||{};const id=p.id||c.personId;const name=p.displayName||p.canonicalName||p.nameAr||id;return `<div class="task-card"><div class="task-head"><b>${escapeHtml(name)}</b><span class="badge ${c.score>=.86?'low':'medium'}">${Math.round((c.score||0)*100)}%</span></div><button class="primary-btn compact identity-confirm" data-mid="${m.id}" data-pid="${id}">تأكيد</button></div>`;}).join('');return `<div class="task-card"><div class="task-head"><b>${escapeHtml(m.text)}</b><span class="badge medium">${escapeHtml(m.status)}</span></div><div class="hint">الثقة: ${Math.round((m.confidence||0)*100)}%</div>${candidateHtml}<div class="task-actions"><button class="secondary-btn compact identity-new" data-mid="${m.id}">شخص جديد</button><button class="secondary-btn compact identity-defer" data-mid="${m.id}">تأجيل</button></div></div>`;}
function bindIdentityActions(){document.querySelectorAll('.identity-confirm').forEach(b=>b.onclick=()=>reviewIdentity(b.dataset.mid,'resolve',b.dataset.pid));document.querySelectorAll('.identity-new').forEach(b=>b.onclick=()=>reviewIdentity(b.dataset.mid,'new_person'));document.querySelectorAll('.identity-defer').forEach(b=>b.onclick=()=>reviewIdentity(b.dataset.mid,'defer'));}
async function loadIdentityQueue(){const r=await IdentityClient.queue();const box=document.getElementById('identity-results');box.innerHTML=(r.items||[]).map(identityCard).join('')||'<p class="hint">لا توجد إشارات تحتاج مراجعة.</p>';bindIdentityActions();}
async function reviewIdentity(mentionId,action,personId){try{await IdentityClient.review({mentionId,action,personId});await loadIdentityQueue();}catch(e){alert(e.message);}}
document.getElementById('refresh-identity').onclick=()=>loadIdentityQueue().catch(e=>alert(e.message));
document.querySelector('[data-tab="identity"]').addEventListener('click',()=>loadIdentityQueue().catch(()=>{}));
document.getElementById('resolve-identity').onclick=async()=>{const text=document.getElementById('identity-mention').value.trim();if(!text)return alert('اكتب الاسم المذكور.');try{const r=await IdentityClient.resolve({text,context:{text:document.getElementById('identity-context').value.trim()}});document.getElementById('identity-results').innerHTML=identityCard(r.mention);bindIdentityActions();}catch(e){alert(e.message);}};
